### ISSUE TITLE
Permission error with jsons during metadata completion

### ISSUE THREAD

**Issue by tsalo** [fiuneuro/cis-bidsify#48]
Here's the traceback:

```
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/bin/bidsify", line 8, in <module>
    sys.exit(_main())
  File "/opt/conda/envs/neuro/lib/python3.7/site-packages/bidsify/bidsify.py", line 211, in _main
    bidsify_workflow(**kwargs)
  File "/opt/conda/envs/neuro/lib/python3.7/site-packages/bidsify/bidsify.py", line 159, in bidsify_workflow
    clean_metadata(output_dir, subject, session)
  File "/opt/conda/envs/neuro/lib/python3.7/site-packages/bidsutils/metadata.py", line 173, in clean_metadata
    with open(json_file, 'w') as fo:
PermissionError: [Errno 13] Permission denied: '/home/data/nbc/Laird_DIVA/temp_dset/sub-Blossom/ses-01/fmap/sub-Blossom_ses-01_acq-func_dir-AP_run-01_epi.json'
```

**Comment by tsalo** [comment]
Oddly enough, everything in `fmap/` is r--r--r--, while everything in `func/` is rw-r--r--.
