### ISSUE TITLE
Validator error in Singularity

### ISSUE THREAD

**Issue by tsalo** [fiuneuro/cis-bidsify#51]
Traceback:
```
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/bin/bidsify", line 8, in <module>
    sys.exit(_main())
  File "/opt/conda/envs/neuro/lib/python3.7/site-packages/bidsify/bidsify.py", line 223, in _main
    bidsify_workflow(**kwargs)
  File "/opt/conda/envs/neuro/lib/python3.7/site-packages/bidsify/bidsify.py", line 174, in bidsify_workflow
    run(cmd, env={'TMPDIR': work_dir.name})
  File "/opt/conda/envs/neuro/lib/python3.7/site-packages/bidsify/utils.py", line 36, in run
    raise Exception(f"Non zero return code: {process.returncode}\n"
Exception: Non zero return code: 1
bids-validator /home/data/nbc/Laird_DIVA/temp_dset --ignoreWarnings > /home/data/nbc/Laird_DIVA/work-dir/Blossom-01/validator.txt

b''
```

The dataset counted as invalid, but that shouldn't be a problem at this stage.

**Comment by tsalo** [comment]
The preferred behavior is to not raise an error if the validator fails (meaning dataset is invalid, not validator is broken). It should just write out the relevant file.
